[package]
name = "bevy_window"
version = "0.15.2"
edition = "2021"
description = "Provides windowing functionality for Bevy Engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[features]
default = ["bevy_reflect"]
serialize = ["serde", "smol_str/serde", "bevy_ecs/serialize"]
bevy_reflect = ["dep:bevy_reflect"]
# bevy_reflect = ["dep:bevy_reflect", "bevy_input/bevy_reflect"]

[dependencies]
# bevy
bevy_a11y = { path = "../bevy_a11y", version = "0.15.2" }
bevy_app = { path = "../bevy_app", version = "0.15.2" }
bevy_ecs = { path = "../bevy_ecs", version = "0.15.2" }
bevy_input = { path = "../bevy_input", version = "0.15.2" }
bevy_math = { path = "../bevy_math", version = "0.15.2" }
bevy_reflect = { path = "../bevy_reflect", version = "0.15.2", features = [
  "glam",
  "smol_str",
], optional = true}
bevy_utils = { path = "../bevy_utils", version = "0.15.2" }

# other
serde = { version = "1.0", features = ["derive"], optional = true }
raw-window-handle = "0.6"
smol_str = "0.2"

[target.'cfg(target_os = "android")'.dependencies]
android-activity = "0.6"

[lints]
workspace = true

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--generate-link-to-definition"]
all-features = true
